### ISSUE TITLE
Migration of Alert Issue

### ISSUE THREAD

**Issue by Nkwayep** [blackducksoftware/alert-issue-property-indexer#4]
Hello Team,
please we have an app **Alert Issue Property Indexer** on Jira server and I want to ask how the data are store in jira and how I can migrate this app to jira cloud?

Thank you in advance,

Best Regards,

Chimène

**Comment by mau-mscs** [comment]
Our plugin does not store data in Jira and you can migrate by just installing the plugin on Jira Cloud
