### ISSUE TITLE
Release for Jira Datacenter 9.x (9.4)

### ISSUE THREAD

**Issue by donaldm** [blackducksoftware/alert-issue-property-indexer#7]
We would like to use this plugin, but we use Jira Datacenter 9.4.

Can a new release be made that is compatible with this version?

Thank you

**Comment by mau-mscs** [comment]
Jira software 9.4.5 was made compatible with 0.0.3 version of the plugin May 30, 2023 https://github.com/blackducksoftware/alert-issue-property-indexer/pull/8
