### ISSUE TITLE
Datacenter 9.11.0 support for plugin

### ISSUE THREAD

**Issue by zsgaikwad** [blackducksoftware/alert-issue-property-indexer#9]
when can we have supported version of this plugin for Jira DC 9.11.0 https://marketplace.atlassian.com/apps/1220957/alert-issue-property-indexer?hosting=datacenter&tab=support

**Comment by mau-mscs** [comment]
Updated to support up to 9.12.0 as of Jan 30, 2024 https://github.com/blackducksoftware/alert-issue-property-indexer/pull/10
